/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { LatestReleases } from "./LatestReleases";
import { LatestReleasesCountArgs } from "./LatestReleasesCountArgs";
import { LatestReleasesFindManyArgs } from "./LatestReleasesFindManyArgs";
import { LatestReleasesFindUniqueArgs } from "./LatestReleasesFindUniqueArgs";
import { DeleteLatestReleasesArgs } from "./DeleteLatestReleasesArgs";
import { LatestReleasesService } from "../latestReleases.service";
@graphql.Resolver(() => LatestReleases)
export class LatestReleasesResolverBase {
  constructor(protected readonly service: LatestReleasesService) {}

  async _latestReleasesItemsMeta(
    @graphql.Args() args: LatestReleasesCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [LatestReleases])
  async latestReleasesItems(
    @graphql.Args() args: LatestReleasesFindManyArgs
  ): Promise<LatestReleases[]> {
    return this.service.latestReleasesItems(args);
  }

  @graphql.Query(() => LatestReleases, { nullable: true })
  async latestReleases(
    @graphql.Args() args: LatestReleasesFindUniqueArgs
  ): Promise<LatestReleases | null> {
    const result = await this.service.latestReleases(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => LatestReleases)
  async deleteLatestReleases(
    @graphql.Args() args: DeleteLatestReleasesArgs
  ): Promise<LatestReleases | null> {
    try {
      return await this.service.deleteLatestReleases(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
